project_id = "rdagqukqmphvlxbrefil"

[functions.check-license]
verify_jwt = false

[functions.get-script]
verify_jwt = false

[functions.check-expiring-licenses]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.check-pix-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mp-oauth-start]
verify_jwt = false

[functions.mp-oauth-callback]
verify_jwt = false

[functions.audit-suspicious-purchases]
verify_jwt = false

