// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-scripts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { z } from "npm:zod@^3.25.76";
var search_scripts_default = defineTool({
  name: "search_scripts",
  title: "Search marketplace scripts",
  description: "Search published HiddenMod marketplace scripts for Game Guardian. Filter by keyword, game name, or paid/free.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search over title, description and game name."),
    game: z.string().optional().describe("Filter by game name (case-insensitive contains)."),
    only_free: z.boolean().optional().describe("If true, only return free scripts."),
    only_paid: z.boolean().optional().describe("If true, only return paid scripts."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, game, only_free, only_paid, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("scripts").select(
      "id, title, description, game_name, is_paid, price, average_rating, total_ratings, download_count, tags, created_at"
    ).eq("publish_status", "published").eq("is_active", true).order("download_count", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%,game_name.ilike.%${query}%`);
    if (game) q = q.ilike("game_name", `%${game}%`);
    if (only_free) q = q.eq("is_paid", false);
    if (only_paid) q = q.eq("is_paid", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scripts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-script.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_script_default = defineTool2({
  name: "get_script",
  title: "Get script details",
  description: "Fetch full public details for a HiddenMod script by its UUID.",
  inputSchema: {
    id: z2.string().uuid().describe("The script UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    const { data, error } = await supabase.from("scripts").select(
      "id, title, description, game_name, version, features, tags, is_paid, price, license_duration_days, average_rating, total_ratings, download_count, is_verified, script_type, video_url, thumbnail_url, created_at, updated_at"
    ).eq("id", id).eq("publish_status", "published").eq("is_active", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Script not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { script: data }
    };
  }
});

// src/lib/mcp/tools/list-tutorials.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_tutorials_default = defineTool3({
  name: "list_tutorials",
  title: "List tutorials",
  description: "List HiddenMod tutorials about Game Guardian, emulators, Lua scripting, etc.",
  inputSchema: {
    query: z3.string().optional().describe("Optional keyword filter (title/description)."),
    category: z3.string().optional().describe("Optional category filter."),
    limit: z3.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("tutorials").select("id, title, description, category, thumbnail_url, video_url, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (query) q = q.or(`title.ilike.%${query}%,description.ilike.%${query}%`);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { tutorials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-bounties.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.95.3";
import { z as z4 } from "npm:zod@^3.25.76";
var list_bounties_default = defineTool4({
  name: "list_bounties",
  title: "List open bounties",
  description: "List HiddenMod bounties (script requests) with their reward and status.",
  inputSchema: {
    status: z4.enum(["open", "in_progress", "completed", "cancelled"]).optional(),
    game: z4.string().optional().describe("Filter by game name (contains)."),
    limit: z4.number().int().min(1).max(50).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, game, limit }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false } }
    );
    let q = supabase.from("bounties").select("id, title, description, game_name, reward_amount, status, deadline, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    else q = q.eq("status", "open");
    if (game) q = q.ilike("game_name", `%${game}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { bounties: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "hiddenmod-mcp",
  title: "HiddenMod MCP",
  version: "0.1.0",
  instructions: "HiddenMod is a marketplace of Lua scripts for Game Guardian. Use `search_scripts` and `get_script` to browse marketplace scripts, `list_tutorials` to find Game Guardian / emulator / Lua tutorials, and `list_bounties` to see open script requests. All tools are read-only and return public catalog data.",
  tools: [search_scripts_default, get_script_default, list_tutorials_default, list_bounties_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
